# Generated by Django 3.0 on 2024-08-13 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('placa_do_carro', models.CharField(max_length=11, verbose_name='Placa do Carro')),
                ('numero_da_casa', models.CharField(max_length=11, verbose_name='Número da Casa')),
                ('hora_da_chegada', models.TimeField(max_length=11, verbose_name='Hora da Chegada')),
                ('hora_da_saida', models.TimeField(max_length=11, verbose_name='Hora da Saída')),
                ('hora_da_autorizacao', models.TimeField(max_length=11, verbose_name='Hora da Autorização')),
                ('nome_do_morador', models.CharField(max_length=100, verbose_name='Nome do Morador')),
                ('porteiro_que_autorizou', models.CharField(max_length=100, verbose_name='Porteiro que Autorizou')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Visitante',
                'verbose_name_plural': 'Visitantes',
                'db_table': 'visitante',
            },
        ),
    ]
