# Generated by Django 3.0 on 2024-08-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitante',
            name='registrado_por',
            field=models.CharField(max_length=150, verbose_name='Nome Completo'),
        ),
    ]
